//! JPXDecode (JPEG 2000) image decoding against fixtures generated by
//! `fixtures/gen_jpx_fixtures.py` (lossless fixtures ship byte-exact `.raw`
//! references dumped at generation time).

use zpdf_core::{PdfDict, PdfName, PdfObject};
use zpdf_image::{decode_image_xobject, DecodedImage};

const W: u32 = 32;
const H: u32 = 24;

const RGB_JP2: &[u8] = include_bytes!("fixtures/rgb.jp2");
const RGB_REF: &[u8] = include_bytes!("fixtures/rgb_ref.raw");
const GRAY_J2K: &[u8] = include_bytes!("fixtures/gray.j2k");
const GRAY_REF: &[u8] = include_bytes!("fixtures/gray_ref.raw");
const RGBA_JP2: &[u8] = include_bytes!("fixtures/rgba.jp2");
const RGBA_REF: &[u8] = include_bytes!("fixtures/rgba_ref.raw");
const RGB_LOSSY_JP2: &[u8] = include_bytes!("fixtures/rgb_lossy.jp2");
const RGB_LOSSY_REF: &[u8] = include_bytes!("fixtures/rgb_lossy_ref.raw");

/// Image dict as a PDF would carry it: /Width and /Height are required keys,
/// while /ColorSpace and /BitsPerComponent may be omitted for JPXDecode.
fn jpx_dict(width: i64, height: i64) -> PdfDict {
    let mut d = PdfDict::new();
    d.insert(PdfName::new("Width"), PdfObject::Integer(width));
    d.insert(PdfName::new("Height"), PdfObject::Integer(height));
    d.insert(
        PdfName::new("Filter"),
        PdfObject::Name(PdfName::new("JPXDecode")),
    );
    d
}

fn px(img: &DecodedImage, i: usize) -> &[u8] {
    &img.data[i * 4..i * 4 + 4]
}

#[test]
fn rgb_jp2_decodes_pixel_exact() {
    let img = decode_image_xobject(RGB_JP2, &jpx_dict(W as i64, H as i64)).unwrap();
    assert_eq!((img.width, img.height), (W, H));
    assert!(!img.has_alpha);
    for i in 0..(W * H) as usize {
        let want = &RGB_REF[i * 3..i * 3 + 3];
        assert_eq!(px(&img, i), &[want[0], want[1], want[2], 255], "pixel {i}");
    }
}

#[test]
fn gray_raw_codestream_decodes_pixel_exact() {
    let img = decode_image_xobject(GRAY_J2K, &jpx_dict(W as i64, H as i64)).unwrap();
    assert_eq!((img.width, img.height), (W, H));
    for (i, &g) in GRAY_REF.iter().enumerate().take((W * H) as usize) {
        assert_eq!(px(&img, i), &[g, g, g, 255], "pixel {i}");
    }
}

#[test]
fn magic_sniffing_without_filter_entry() {
    // No /Filter at all (e.g. the producer pre-decompressed an outer Flate):
    // the JP2 signature box in the data should still route to the JPX decoder.
    let mut d = PdfDict::new();
    d.insert(PdfName::new("Width"), PdfObject::Integer(W as i64));
    d.insert(PdfName::new("Height"), PdfObject::Integer(H as i64));
    let img = decode_image_xobject(RGB_JP2, &d).unwrap();
    assert_eq!((img.width, img.height), (W, H));
    assert_eq!(px(&img, 0)[..3], RGB_REF[..3]);
}

#[test]
fn rgba_without_smask_in_data_is_opaque() {
    // /SMaskInData 0/absent: codestream alpha shall be ignored (spec 7.4.9).
    let img = decode_image_xobject(RGBA_JP2, &jpx_dict(W as i64, H as i64)).unwrap();
    assert!(!img.has_alpha);
    for i in 0..(W * H) as usize {
        let want = &RGBA_REF[i * 4..i * 4 + 4];
        assert_eq!(px(&img, i), &[want[0], want[1], want[2], 255], "pixel {i}");
    }
}

#[test]
fn rgba_with_smask_in_data_premultiplies() {
    let mut dict = jpx_dict(W as i64, H as i64);
    dict.insert(PdfName::new("SMaskInData"), PdfObject::Integer(1));
    let img = decode_image_xobject(RGBA_JP2, &dict).unwrap();
    assert!(img.has_alpha);
    assert!(img.premultiplied);
    let mul255 = |v: u8, a: u8| ((v as u32 * a as u32 + 127) / 255) as u8;
    for i in 0..(W * H) as usize {
        let want = &RGBA_REF[i * 4..i * 4 + 4];
        let a = want[3];
        assert_eq!(
            px(&img, i),
            &[
                mul255(want[0], a),
                mul255(want[1], a),
                mul255(want[2], a),
                a
            ],
            "pixel {i}"
        );
    }
}

#[test]
fn lossy_jp2_decodes_close_to_reference() {
    // Irreversible 9/7 wavelet: compare codec-to-codec against OpenJPEG's
    // decode of the same file (dumped at fixture-generation time) with a
    // small float-rounding tolerance.
    let img = decode_image_xobject(RGB_LOSSY_JP2, &jpx_dict(W as i64, H as i64)).unwrap();
    assert_eq!((img.width, img.height), (W, H));
    let mut total: u64 = 0;
    let mut worst: u8 = 0;
    for i in 0..(W * H) as usize {
        for c in 0..3 {
            let d = px(&img, i)[c].abs_diff(RGB_LOSSY_REF[i * 3 + c]);
            total += d as u64;
            worst = worst.max(d);
        }
    }
    let mean = total as f64 / (W as f64 * H as f64 * 3.0);
    assert!(mean < 0.5, "mean abs error vs OpenJPEG {mean}");
    assert!(worst <= 2, "worst pixel diff vs OpenJPEG {worst}");
}

#[test]
fn codestream_dimensions_override_dict() {
    // The codestream is authoritative when the dict disagrees.
    let img = decode_image_xobject(RGB_JP2, &jpx_dict(1, 1)).unwrap();
    assert_eq!((img.width, img.height), (W, H));
}

#[test]
fn garbage_with_jpx_filter_errors_cleanly() {
    let err = decode_image_xobject(b"not a codestream", &jpx_dict(4, 4));
    assert!(err.is_err());
}

#[test]
fn truncated_codestream_errors_cleanly() {
    // Valid magic, then cut off mid-stream: must error, never panic.
    for len in [4usize, 12, 40, GRAY_J2K.len() / 2] {
        let res = decode_image_xobject(&GRAY_J2K[..len], &jpx_dict(W as i64, H as i64));
        assert!(res.is_err(), "len {len} should fail");
    }
}

#[test]
fn oversized_codestream_dimensions_rejected() {
    // Patch the SIZ marker's Xsiz/Ysiz (big-endian u32 at byte offsets 8 and
    // 12 of a raw codestream) to 200k x 200k = 4e10 pixels, far past the
    // 100M-pixel cap. Must be rejected before any large allocation.
    let mut data = GRAY_J2K.to_vec();
    let big = 200_000u32.to_be_bytes();
    data[8..12].copy_from_slice(&big);
    data[12..16].copy_from_slice(&big);
    let res = decode_image_xobject(&data, &jpx_dict(W as i64, H as i64));
    assert!(res.is_err());
}
